### ISSUE TITLE
Wayland Issues

### ISSUE THREAD

**Issue by rowbawts** [flathub/dev.goats.xivlauncher#1]
With the Wayland permission (as per default) I get no window decorations and I can't type into the login/password fields removing this permission and using Xwayland resolves both of these.

If anymore information is required to help troubleshoot please ask and I can deliver.

![image](https://user-images.githubusercontent.com/13012832/166939184-73e772fb-a648-46ca-ab95-4dfd1b5e85d5.png)

**Comment by hfiguiere** [comment]
tbd I asked the question in the review:

https://github.com/flathub/flathub/pull/3101#discussion_r864398838

My take? wayland should be disable if it doesn't work.

**Comment by rowbawts** [comment]
> tbd I asked the question in the review:
> 
> [flathub/flathub#3101 (comment)](https://github.com/flathub/flathub/pull/3101#discussion_r864398838)
> 
> My take? wayland should be disabled if it doesn't work.

I was watching the review I saw your comment.

**Comment by rowbawts** [comment]
> Thanks for the heads up, seems like the info I had was incorrect. Probably best to disable it altogether for now.
> 
> SDL apparently needs to be compiled with libdecor support enabled to draw window title bars on Wayland, so there's some work to be done here.
> 
> (I'm rather new to the distribution of Linux apps, sorry for blunders like this)

No problem that's what this community is for, I'm glad to see you guys going out of your way to publish on Flathub. I went ahead an created a pull request for you with the change.
