### ISSUE TITLE
Add dri (GPU Acceleration) access

### ISSUE THREAD

**Issue by sradigan** [flathub/dev.goats.xivlauncher#39]
Adding `device=dri` access showed a noticeable improvement on bazzite using an AMD 6800XT GPU. The game ran fine without this, but it ran better with it.

![2024-01-29_09-00](https://github.com/flathub/dev.goats.xivlauncher/assets/6443966/e75f48a4-f493-4440-b8a0-d248d2a24b86)

**Comment by Adamcake** [comment]
Doesn't `device=all` already imply `device=dri`?

If you turn both of those off, you'll see what it's actually like without dri access. (It's pretty bad.)

I don't understand why this game needs `device=all` though. It doesn't use any other than dri, to my knowledge, unless there's a plugin for mic chat or something.

**Comment by sradigan** [comment]
> Doesn't device=all already imply device=dri?

I don't know that this is true or not. [The docs](https://docs.flatpak.org/en/latest/sandbox-permissions.html#device-access) aren't very clear on this.

I can only really report that performance was enhanced after turning on the `device=dri` explicitly. `device=all` has always been turned on in this instance, so anecdotally (take with a grain of salt) it appears that `device=all` doesn't imply access to dri.
